### ISSUE TITLE
Showing coverage for commits

### ISSUE THREAD

**Issue by springmeyer** [codecov/sourcegraph-codecov#10]
I just installed the extension and I'm seeing diffs on github working for specific files but not for commits. 

For example I don't see coverage showing up https://github.com/mapbox/geometry.hpp/commit/c83a2ab18a225254f128b6f5115aa39d04f2de21 but I do see coverage showing at https://github.com/mapbox/geometry.hpp/blob/c83a2ab18a225254f128b6f5115aa39d04f2de21/include/mapbox/geometry_io.hpp.

I think the commit view is the most valuable place to show coverage. Also the now deprecated https://github.com/codecov/browser-extension used to work this way: it showed coverage for commits.

**Comment by felixfbecker** [comment]
Hi @springmeyer, this is supported now 🎉 

![image](https://user-images.githubusercontent.com/10532611/60979393-f116b400-a332-11e9-9a3a-54178aaab7e3.png)

You can read more in our announcement blog post: https://about.sourcegraph.com/blog/sourcegraph-3.5#improved-code-reviews-with-line-decorations-in-pull-requests
