### ISSUE TITLE
Coverage overlay for PRs

### ISSUE THREAD

**Issue by jarekwg** [codecov/sourcegraph-codecov#23]
Related to #10,
But would be really awesome to have the overlay on the diff overview for PRs.
ie on this page `https://github.com/<org>/<repo>/pull/<#pr>/files`

The old codecov extension offered this and it was amazing. After submitting a PR, one could see which lines of the code they'd touched were covered.

It was especially nice how it'd continue to use a darker green/red highlighting in the line number gutter to indicate which lines were added/removed, whilst the lighter green/red highlighting across the actual code indicated what lines were covered by tests.

All the best. :)

**Comment by felixfbecker** [comment]
This depends on https://github.com/sourcegraph/sourcegraph/issues/911, I have a WIP prototype PR up at https://github.com/sourcegraph/sourcegraph/issues/911

**Comment by felixfbecker** [comment]
Hi @jarekwg, this is supported now 🎉
You can see it in action in our announcement blog post: https://about.sourcegraph.com/blog/sourcegraph-3.5#improved-code-reviews-with-line-decorations-in-pull-requests

**Comment by jarekwg** [comment]
Awesome stuff! Thanks! Will jump onto it quicksmart.

**Comment by jberryman** [comment]
Where would I find docs on this? Videos in that blog are broken

**Comment by dkrotx-test** [comment]
As I understand this is now deprecated. Any plans on resurrecting this amazing overlay feature?

**Comment by thomasrockhu** [comment]
@dkrotx-test we are starting to look at creating an overlay feature. You can follow along [here](https://github.com/codecov/codecov-browser-extension)
