### ISSUE TITLE
Decorations not appearing on GitHub

### ISSUE THREAD

**Issue by ryan-blunden** [codecov/sourcegraph-codecov#29]
I can see the Codecov button and test coverage decorations on Sourcegraph but not GitHub for file https://github.com/theupdateframework/notary/blob/fb795b0bc868746ed2efa2cd7109346bc7ddf0a4/server/storage/tuf_store.go

![codecov](https://user-images.githubusercontent.com/133014/58598515-92d5bc00-8231-11e9-84c4-4ac132481cdf.gif)

**Comment by ryan-blunden** [comment]
This seems to be an issue with the branch name as if you change the branch to master, it works.

**Comment by felixfbecker** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/4281.
Closing here as not an issue with the extension.
