### ISSUE TITLE
repo with no coverage data shows console errors

### ISSUE THREAD

**Issue by sqs** [codecov/sourcegraph-codecov#3]
eg http://localhost:3080/github.com/sourcegraph/go-langserver@bf90fac03a4d1a07f50701547d56fabfdb0c32ec/-/blob/langserver/loader.go#L29:30

![image](https://user-images.githubusercontent.com/1976/43940350-121039ae-9c24-11e8-984a-6c3bc2dc1fe2.png)

**Comment by chrismwendt** [comment]
I believe Codecov needs to allow other origins on their 404 page, and I've informed them of this.

**Comment by lguychard** [comment]
Fixed in https://github.com/codecov/sourcegraph-codecov/pull/41
