### ISSUE TITLE
Plugin does not work for private repository

### ISSUE THREAD

**Issue by Elliot128** [codecov/sourcegraph-codecov#44]
After following the instructions in the readme for private repos, my console has an Uncaught RepoNotFoundError error when viewing my private repo.

After contacting codecov support, they told me to do the following:

* navigate to chrome://extensions
* enable developer mode (top-right corner)
* Inspect the background page of the sourcegraph extension
* reload the code page on GitHub page in a browser tab
* check the chrome dev tools for the extension’s background page
* In the “Network” tab, the ResolveRev, ResolveRepo steps should return 200

The network tab did not have any activity.

Is there anything else that needs to be done that's not in the readme? For what its worth, I do see a "Configure sourcegraph" button.

**Comment by christinaforney** [comment]
Hi @Elliot128 - thanks for reporting! This might be regression, and the team is looking into it. Stay tuned!

**Comment by Elliot128** [comment]
I can confirm this is now working, thanks for the fast response!
