### ISSUE TITLE
Broken Codecov test coverage background colors?

### ISSUE THREAD

**Issue by esambo** [codecov/sourcegraph-codecov#56]
I cannot seem to get the code coverage background color to show up in GitHub for the [example mentioned in the _usage_ section of the README](https://github.com/codecov/sourcegraph-codecov#on-github-using-the-chrome-extension). Perhaps the recent [GitHub UI change from June 23rd](https://github.blog/changelog/2020-06-23-design-updates-to-repositories-and-github-ui/) broke it?

**Comment by lguychard** [comment]
Hi @esambo, looks like the link in the usage section of the README referenced a commit whose coverage report is no longer stored on codecov.io. #57 fixes this link, with the [updated link](https://github.com/theupdateframework/notary/blob/54749226dfcace398bbffe27f63564d50d1cf025/server/storage/tuf_store.go) the code coverage background is correctly shown:

![image](https://user-images.githubusercontent.com/1741180/91863786-c773c700-ec6f-11ea-91b9-0024ce9a979a.png)
